server:
  port: 8080

spring:
  application:
    name: shadow-admin
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shadow
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    max-idle: 10
    max-active: 15
    max-lifetime: 86430000
    log-abandoned: true
    remove-abandoned: true
    remove-abandoned-timeout: 60
    sqlScriptEncoding: UTF-8
