server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shadow?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Hs123456

  redis:
      host: 127.0.0.1
      port: 6379

