server:
  port: 8080

spring:
  application:
    name: shadow-admin-api
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss:SSS
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
      file-size-threshold: 0
      enabled: true